## YAML Jeykyll Config

## WARNING: need to restart Jkyll when updated !!!
## -----------------------------------------------

title: Iot.bzh Technical WebDoc
home : https://github.com/iotbzh/iotbzh.github.io

attributions:
    author   : Fulup Ar Foll
    copyright: IoT.bzh
    licence  : http://www.apache.org/licenses/LICENSE-2.0
    home     : http://iot.bzh

# usefull internal options
markdown:  kramdown
redirects: yes
kramdown: 
  toc_levels: "2,3"
  
destination: _site

# place here optionnal gem plugins (need to be installed locally with gem install and present on github)
gems:
  - jekyll-redirect-from
  
assets: 
    js:    /statics/js
    img:   /statics/img
    logo:  /statics/logo/iotbzh-logo.svg
    stamp: /statics/logo/iotbzh-stamp.png
    icone: /statics/logo/triskel_iot_bzh.svg
    
sass:
    template : /statics/styles/templates
    sass_dir : /statics/styles/sasslib
    style: compressed

graph: # ~~~ UML-style-class
    def_style: simple 
    tag_uml  : UML 
    tag_flow : FLOW
    debug    : false
    